const data = {
verite:[
    {question:"	Dans ce groupe, qui amènerais-tu avec toi sur une île déserte ?"},
    {question:"	Raconte la plus grande honte que tu as vécue ?"},
    {question:"	Quel est le rêve le plus étrange que tu aies fait ?"},
    {question:"	Quel est ton plus grand secret ?"},
    {question:"	Si aujourd’hui était le dernier jour de ta vie, que ferais-tu ?"},
    {question:"	De 0 à 10. Quelle note donnerais-tu (choisir quelqu'un du groupe) en beauté, sympathie ou intelligence ?"},
    {question:"	De 0 à 10. Quelle note te donnerais-tu à toi-même en beauté, sympathie ou intelligence ?"},
    {question:"	Quel est le pire cadeau que tu aies jamais reçu ?"},
    {question:"	Quel est le meilleur cadeau qu'on t'ait jamais fait ?"},
    {question:"	Si c'était la fin du monde et que tu ne pouvais sauver qu'une seule personne, qui serait-elle ?"},
    {question:"	As-tu déjà nagé nu dans l'eau ?"},
    {question:"	Est-ce que quelqu'un t'a déjà trahi ?"},
    {question:"	Qu'est-ce qui manquera jamais dans ton frigo ?"},
    {question:"	Est-ce que tu pourrais coucher avec quelqu'un pour beaucoup d'argent ?"},
    {question:"	As-tu déjà envoyé une photo coquine par portable ?"},
    {question:"	As-tu déjà embrassé plusieurs personnes le même jour ?, Si oui, combien ?"},
    {question:"	De quoi es-tu le/la plus fier.e ?"},
    {question:"	Te crois-tu attirant.e ?"},
    {question:"	Si tu pouvais ramener une personne décédée à la vie, qui serait-elle ?"},
    {question:"	Si tu pouvais voyager dans le temps, à quelle époque irais-tu ?"},
    {question:"	As-tu menti en jouant à ce jeu ?"},
    {question:"	Quelle est ta technique de séduction ?"},
    {question:"	Quel le plus grand mensonge que tu aies raconté ?"},
    {question:"	Quelle est la pire connerie que t'aies jamais faite ?"},
    {question:"	Quel est ton plus gros regret ?"},
    {question:"	Quel est ton plus gros remords ?"},
    {question:"	Ton plus gros complexe ?"},
    {question:"	T'as déjà été bourré.e ? Si oui, raconte-nous ce qu'il s'est passé pendant ta soirée la plus alcoolisée.?"},
    {question:"	Tas déjà fumé une clope ?"},
    {question:"	T'as déjà fait une nuit blanche ?"},
    {question:"	C'est qui ton meilleur ami ?"},
    {question:"	C'est qui ta meilleure amie ?"},
    {question:"	Raconte-nous un secret de ton enfance."},
    {question:"	T'as déjà commis un délit ?"},
    {question:"	T'as déjà été arrêté par la police ?"},
    {question:"	Quel est le pire truc que t'aies jamais fait ?"},
    {question:"	Ta destination rêvée pour partir en vacances ?"},
    {question:"	Quel est le membre préféré de ta famille ?"},
    {question:"	Quelle est la célébrité que tu trouves le plus beau ?"},
    {question:"	Quelle est la célébrité que tu trouves la plus belle ?"},
    {question:"	T'as déjà pété dans un ascenseur ?"},
    {question:"	Tu t'es déjà fait pipi dessus, si oui, raconte-nous tout!"},
    {question:"	Tu t'es déjà fait caca dessus, si oui, raconte-nous l'histoire complète!"},
    {question:"	T'as déjà été amoureux.se ?"},
    {question:"	T'as déjà souhaité du mal de quelqu'un, si oui, de qui ?"},
    {question:"	Avec quelle personne célèbre tu coucherais ?"},
    {question:"	T'as aimé la fin de GoT (Game of Thrones) ?"},
    {question:"	T'es déjà parti.e sans payer l'addition ?"},
    {question:"	C'est quoi ton plat préféré ?"},
    {question:"	T'as déjà entendu tes parents en train de le faire ?"},
    {question:"	Tu ronfles ?"},
    {question:"	Tu t'es déjà fait pipi dessus en dormant ?"},
    {question:"	Tu crois en Dieu ?"},
    {question:"	Tu crois au destin ?"},
    {question:"	Est-ce que t'as une manie bizarre ?"},
    {question:"	Tu ferais Koh Lanta ?"},
    {question:"	T'as un TOC ?"},
    {question:"	Tu te rases les parties intimes ?"},
    {question:"	Tu crois au coup de foudre ?"},
    {question:"	Quelle est la pire chose qui pourrait t'arriver ?"},
    {question:"	Que penses-tu d'Emmanuel Macron ?"},
    {question:"	Tu soutiens les gilets jaunes ?"},
    {question:"	Quel est l'âge de ton premier bisous ?"},
    {question:"	Si tu devais avoir un tatouage, ce serait quoi et où il serait ?"},
    {question:"	Lequel des 7 péchés capitaux dirige ta vie ?"},
    {question:"	Quel est ton film préféré ?"},
    {question:"	T'es vierge ?"},
    {question:"	À quel âge as-tu perdu ta virginité ?"},
    {question:"	T'as déjà dormi dans la rue ?"},
    {question:"	T'as déjà volé quelque chose, si oui, c'était quoi ?"},
    {question:"	Si tu devais rencontrer une de tes idoles, morte ou vivante, qui serait-elle et pourquoi ?"},
    {question:"	Qui tu mettrais sur des billets de banque ?"},
    {question:"	Tu fais pipi sous la douche ?"},
    {question:"	Une fois que t'as fait caca, tu utilises combien de feuilles de papier toilette ?"},
    {question:"	Quel est le concert auquel tu rêverais d'assister ?"},
    {question:"	T'as déjà rembourré ton soutif ou ton slip ?"},
    {question:"	Quelle est la partie du corps que tu préfères chez ton amant.e ?"},
    {question:"	Si tu étais aveugle, qui autour de cette table serait ton chien d'aveugle ?"},
    {question:"	Tu penses que tu chantes bien ?"},
    {question:"	Quelle est la plus grosse erreur que tu aies jamais commise ?"}
],
action:[
    {question : "Servir les boissons de tout le monde pendant toute la soirée" , point: 3},
    {question : "Faire le plus de pompes possible pendant 1 minute ?", point: 3},
    {question : "Ne pas regarder son téléphone pendant 2 heures ?", point: 3},
    {question : "Modifier le statut de sa relation sur Facebook ?", point: 3},
    {question : "Poster une photo moche sur Instagram ?", point: 3},
    {question : "Draguer un inconnu ?", point: 3},
    {question : "Imiter une scène de film ?", point: 3},
    {question : "Imiter quelqu'un dans le groupe ?", point: 3},
    {question : "Manger de l'ail cru ?", point: 3},
    {question : "Manger une cuillerée de cannelle en poudre ?", point: 3},
    {question : "Appeler votre mère pour lui dire que vous l'aimez ?", point: 3},
    {question : "Fermer les yeux et essayer de reconnaître quelqu'un à sa simple odeur. ?", point: 3},
    {question : "Embrassez la personne que vous trouvez le/la plus beau/belle ?", point: 3},
    {question : "Parler en verlan toute la soirée ?", point: 3},
    {question : "Parler avec un accent, de votre choix, toute la soirée ?", point: 3},
    {question : "Ne pas fumer de toute la soirée ?", point: 3},
    {question : "Faire des compliments pendant toute la soirée ?", point: 3},
    {question : "Avant de jouer, vous devez vous lever et faire un tour sur vous-même ?", point: 3},
    {question : "Ne plus pouvoir dire ni oui ni non toute la soirée ?", point: 3},
    {question : "Se mettre des chaussettes sur vos mains ?", point: 3},
    {question : "Garder ses lunettes à l'envers ?", point: 3},
    {question : "Faire l'arbre droit ?", point: 3},
    {question : "Mettre j'ai pété en statut Facebook ?", point: 3},
    {question : "Envoyez un snap d'une grimace à tous vos contacts ?", point: 3},
    {question : "Ne plus pouvoir utiliser le mot 'boire' toute la soirée ?", point: 3},
    {question : "Inverser votre main dominante, si vous êtes droitier, faites tout avec la main gauche et inversement ?", point: 3},
    {question : "Réciter une fable de De La Fontaine ?", point: 3},
    {question : "Parler en anglais toute la soirée ?", point: 3},
    {question : "Faire un cadeau à une autre personne du groupe ?", point: 3},
    {question : "Ponctuer toutes vos phrases d'un gros mot ?", point: 3},
    {question : "Se laisser maquiller ?", point: 3},
    {question : "Faire une déclaration ?", point: 3},
    {question : " Ponctuer votre phrase d'un 'Dab' ?", point: 3},
    {question : "Essayer de convaincre un membre du groupe que la dernière saison de GoT est bien ?", point: 3},
    {question : "Faire un strip-tease  ?", point: 3},
    {question : "Mettre ses chaussures sur les mains ?", point: 3},
    {question : "Faire une danse honteuse sur les L5 ou les One Direction ?", point: 3},
    {question : "Faire le ménage tout au long de la soirée ?", point: 3},
    {question : "Courir tout.e nu.e dans l'escalier ?", point: 3},
    {question : "Lécher les pieds d'une personne du groupe ?", point: 3},
    {question : "Montrer une photo où vous êtes honteux.se ?", point: 3},
    {question : "Twerker ?", point: 3},
    {question : "Faire un bisou dans le cou à un.e membre du groupe ?", point: 3},
]
}

export default data