export const AFF_EXEMPLE = "AFF_EXEMPLE";
export const NB_PLAYERS = "NB_PLAYERS";
export const LIST_PLAYERS = "LIST_PLAYERS";
export const RANDOM_QUESTION_BY_PLAYERS = "RANDOM_QUESTION_BY_PLAYERS";
export const CURRENT_PLAYER = "CURRENT_PLAYER";
export const SESSION_PLAYER = "SESSION_PLAYER";
